"""Team Management API — invitations, member management, RBAC validation."""
from __future__ import annotations

import secrets
import time
from datetime import datetime, timezone
from typing import Dict, Optional, Set

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel

from utils.email_service import send_invitation_email
from utils.logger import get_logger

logger = get_logger(__name__)
router = APIRouter(prefix="/team", tags=["Team"])

# ── In-memory stores ──────────────────────────────────────────────────
# Complements Firestore (source of truth).
# Stores email invite tokens (sensitive, never written to Firestore).
# Link invite tokens are managed purely in Firestore by the frontend.

_INVITES: Dict[str, dict] = {}         # token → invite data (email invites only)
_ORG_ADMINS: Dict[str, Set[str]] = {}  # orgId → {adminUid, ...}

_INVITE_TTL  = 72 * 3600
_VALID_ROLES = {"admin", "editor", "viewer"}


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


# ── Request / response models ─────────────────────────────────────────

class RegisterOrgBody(BaseModel):
    orgId:    str
    adminUid: str
    orgName:  str


class InviteEmailBody(BaseModel):
    orgId:       str
    orgName:     str
    inviterUid:  str
    inviterName: str
    email:       str
    role:        str
    inviteId:    str   # Firestore doc ID generated by frontend


class ResendInviteBody(BaseModel):
    orgId:       str
    orgName:     str
    inviterUid:  str
    inviterName: str
    inviteId:    str
    email:       str
    role:        str


class CancelInviteBody(BaseModel):
    orgId:    str
    adminUid: str


class AcceptEmailInviteBody(BaseModel):
    token:     str
    userId:    str
    userName:  str
    userEmail: str


class RejectInviteBody(BaseModel):
    token: str


class ChangeRoleBody(BaseModel):
    orgId:     str
    adminUid:  str
    targetUid: str
    newRole:   str


class MemberActionBody(BaseModel):
    orgId:     str
    adminUid:  str
    targetUid: str


class TestEmailBody(BaseModel):
    to_email: str


# ── Routes ────────────────────────────────────────────────────────────

@router.post("/org/register")
async def register_org(body: RegisterOrgBody) -> dict:
    """Register an org and its owner in backend memory."""
    _ORG_ADMINS.setdefault(body.orgId, set()).add(body.adminUid)
    logger.info("Org registered: %s admin=%s", body.orgId, body.adminUid)
    return {"ok": True}


@router.post("/invite/email")
async def invite_by_email(body: InviteEmailBody) -> dict:
    """Generate a secure email invitation token and send it."""
    if body.role not in _VALID_ROLES:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, f"Role must be one of {_VALID_ROLES}")

    token      = secrets.token_urlsafe(32)
    expires_at = time.time() + _INVITE_TTL

    _INVITES[token] = {
        "inviteId":    body.inviteId,
        "orgId":       body.orgId,
        "orgName":     body.orgName,
        "inviterUid":  body.inviterUid,
        "inviterName": body.inviterName,
        "email":       body.email,
        "role":        body.role,
        "expiresAt":   expires_at,
        "status":      "pending",
        "type":        "email",
    }

    result = send_invitation_email(
        to_email=body.email,
        inviter_name=body.inviterName,
        org_name=body.orgName,
        role=body.role,
        token=token,
    )

    return {
        "inviteId":  body.inviteId,
        "token":     token,
        "emailSent": result["sent"],
        "emailError": result["error"],
    }


@router.post("/invite/email/resend")
async def resend_email_invite(body: ResendInviteBody) -> dict:
    """Revoke the old email token and issue a new one."""
    for t, inv in list(_INVITES.items()):
        if inv["inviteId"] == body.inviteId:
            del _INVITES[t]
            break

    token      = secrets.token_urlsafe(32)
    expires_at = time.time() + _INVITE_TTL

    _INVITES[token] = {
        "inviteId":    body.inviteId,
        "orgId":       body.orgId,
        "orgName":     body.orgName,
        "inviterUid":  body.inviterUid,
        "inviterName": body.inviterName,
        "email":       body.email,
        "role":        body.role,
        "expiresAt":   expires_at,
        "status":      "pending",
        "type":        "email",
    }

    result = send_invitation_email(
        to_email=body.email,
        inviter_name=body.inviterName,
        org_name=body.orgName,
        role=body.role,
        token=token,
    )

    return {
        "inviteId":   body.inviteId,
        "token":      token,
        "emailSent":  result["sent"],
        "emailError": result["error"],
    }


@router.get("/invite/verify")
async def verify_email_invite(token: str) -> dict:
    """Return email invitation metadata (no secrets). Used by acceptance page."""
    inv = _INVITES.get(token)
    if not inv:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Invitation not found or already used")
    if inv["status"] != "pending":
        raise HTTPException(status.HTTP_410_GONE, f"Invitation is {inv['status']}")
    if time.time() > inv["expiresAt"]:
        inv["status"] = "expired"
        raise HTTPException(status.HTTP_410_GONE, "Invitation has expired")

    return {
        "inviteId":    inv["inviteId"],
        "orgId":       inv["orgId"],
        "orgName":     inv["orgName"],
        "inviterName": inv["inviterName"],
        "email":       inv["email"],
        "role":        inv["role"],
        "type":        "email",
    }


@router.post("/invite/email/accept")
async def accept_email_invite(body: AcceptEmailInviteBody) -> dict:
    """Validate and consume an email invitation token."""
    inv = _INVITES.get(body.token)
    if not inv:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Invitation not found or already used")
    if inv["status"] != "pending":
        raise HTTPException(status.HTTP_410_GONE, f"Invitation is {inv['status']}")
    if time.time() > inv["expiresAt"]:
        inv["status"] = "expired"
        raise HTTPException(status.HTTP_410_GONE, "Invitation has expired")

    inv["status"] = "accepted"
    del _INVITES[body.token]

    if inv["role"] == "admin":
        _ORG_ADMINS.setdefault(inv["orgId"], set()).add(body.userId)

    logger.info("Email invite accepted: org=%s user=%s role=%s", inv["orgId"], body.userId, inv["role"])
    return {
        "inviteId": inv["inviteId"],
        "orgId":    inv["orgId"],
        "orgName":  inv["orgName"],
        "role":     inv["role"],
    }


@router.post("/invite/email/reject")
async def reject_email_invite(body: RejectInviteBody) -> dict:
    """Reject and consume an email invitation token."""
    inv = _INVITES.get(body.token)
    if not inv:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Invitation not found")
    inv["status"] = "rejected"
    del _INVITES[body.token]
    return {"ok": True, "inviteId": inv.get("inviteId")}


@router.post("/members/role")
async def change_member_role(body: ChangeRoleBody) -> dict:
    if body.newRole not in _VALID_ROLES:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, "Invalid role")
    admins = _ORG_ADMINS.setdefault(body.orgId, set())
    if body.newRole == "admin":
        admins.add(body.targetUid)
    else:
        admins.discard(body.targetUid)
    logger.info("Role changed: org=%s target=%s role=%s by=%s", body.orgId, body.targetUid, body.newRole, body.adminUid)
    return {"ok": True}


@router.post("/members/remove")
async def remove_member(body: MemberActionBody) -> dict:
    _ORG_ADMINS.get(body.orgId, set()).discard(body.targetUid)
    logger.info("Member removed: org=%s target=%s by=%s", body.orgId, body.targetUid, body.adminUid)
    return {"ok": True}


@router.post("/members/disable")
async def disable_member(body: MemberActionBody) -> dict:
    logger.info("Member disabled: org=%s target=%s by=%s", body.orgId, body.targetUid, body.adminUid)
    return {"ok": True}


@router.post("/members/enable")
async def enable_member(body: MemberActionBody) -> dict:
    logger.info("Member enabled: org=%s target=%s by=%s", body.orgId, body.targetUid, body.adminUid)
    return {"ok": True}


@router.post("/email/test")
async def test_email(body: TestEmailBody) -> dict:
    """Send a test email to verify SMTP configuration."""
    result = send_invitation_email(
        to_email=body.to_email,
        inviter_name="Vectra System",
        org_name="Test Organization",
        role="editor",
        token="test-token-do-not-use",
    )
    return {"sent": result["sent"], "error": result["error"]}
